FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN rm requirements.txt

COPY . /app/

CMD ["celery", "-A", "users_services.celery", "worker", "--loglevel=info"]